# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "action_kit_rest"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nathan Woodhull"]
  s.date = "2013-03-13"
  s.description = "Gem for interacting with the ActionKit API"
  s.email = "woodhull@gmail.com"

  s.files = [
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "action_kit_rest.gemspec",
    "lib/action_kit_rest.rb",
    "lib/action_kit_rest/configuration.rb",
    "lib/action_kit_rest/version.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/controlshift/action_kit_rest"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "A wrapper for the ActionKit REST API"

  s.add_runtime_dependency(%q<activesupport>, [">= 0"])
  s.add_runtime_dependency(%q<faraday>, [">= 0"])
  s.add_runtime_dependency(%q<faraday_middleware>, [">= 0"])
  s.add_runtime_dependency(%q<hashie>, [">= 0"])
  s.add_development_dependency(%q<rspec>, [">= 0"])
  s.add_development_dependency(%q<guard>, [">= 0"])
  s.add_development_dependency(%q<guard-rspec>, [">= 0"])
  s.add_development_dependency(%q<pry>, [">= 0"])
  s.add_development_dependency(%q<pry-debugger>, [">= 0"])
  s.add_development_dependency(%q<rb-fsevent>, [">= 0"])
  s.add_development_dependency(%q<rdoc>, [">= 0"])
  s.add_development_dependency(%q<bundler>, [">= 0"])
  s.add_development_dependency(%q<webmock>, [">= 0"])
  s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
  end

